import type { Redis } from "ioredis";

import assert = require("node:assert/strict");
import cookieParser = require("cookie-parser");
import request = require("supertest");

import { ValidationPipe } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { Test } from "@nestjs/testing";

import { AppModule } from "../src/app.module";
import { PrismaService } from "../src/prisma/prisma.service";
import { REDIS_CONNECTION } from "../src/queue/queue.constants";
import { WorkerModule } from "../src/worker/worker.module";
import { WorkerRunner } from "../src/worker/worker.runner";

/**
 * Content pipeline test: admin creates a program -> AI draft generated by the
 * worker (deterministic fallback when AI is off) -> publish -> it appears in
 * the public catalog with day content.
 */
async function main(): Promise<void> {
  process.env.DATABASE_URL =
    process.env.DATABASE_URL || "postgresql://career_pilot:career_pilot@127.0.0.1:5432/career_pilot";

  const moduleRef = await Test.createTestingModule({ imports: [AppModule] }).compile();
  const app = moduleRef.createNestApplication();
  app.setGlobalPrefix("v1");
  app.use(cookieParser());
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: true }));
  await app.init();

  const worker = await NestFactory.createApplicationContext(WorkerModule, { logger: false });
  worker.get(WorkerRunner).start();

  const prisma = app.get(PrismaService);
  const redis = app.get<Redis>(REDIS_CONNECTION);
  const rateLimitKeys = await redis.keys("ratelimit:*");
  if (rateLimitKeys.length) {
    await redis.del(...rateLimitKeys);
  }

  const suffix = Date.now().toString();
  const adminEmail = `authoring-admin-${suffix}@example.com`;
  const tenantSlug = `authoring-${suffix}`;
  const programSlug = `authoring-program-${suffix}`;

  try {
    const register = await request(app.getHttpServer())
      .post("/v1/auth/register")
      .send({
        accountType: "school_admin",
        fullName: "Authoring Admin",
        email: adminEmail,
        password: "authoring1234",
        schoolName: "Authoring School",
        tenantSlug
      })
      .expect(201);
    const cookie = register.headers["set-cookie"]?.[0];
    assert.ok(cookie, "expected admin session cookie");

    const created = await request(app.getHttpServer())
      .post("/v1/admin/programs")
      .set("Cookie", cookie)
      .send({ slug: programSlug, title: "Authoring Test Program", summary: "A program created by the pipeline test." })
      .expect(201);
    const programId = created.body.id;
    assert.ok(programId, "expected created program id");

    const drafted = await request(app.getHttpServer())
      .post(`/v1/admin/programs/${programId}/draft`)
      .set("Cookie", cookie)
      .send({ durationDays: 5 })
      .expect(201);
    assert.equal(typeof drafted.body.queued, "boolean");

    // Poll admin list until a draft version exists.
    let versionId: string | null = null;
    const deadline = Date.now() + 30_000;
    while (Date.now() < deadline) {
      const list = await request(app.getHttpServer()).get("/v1/admin/programs").set("Cookie", cookie).expect(200);
      const program = list.body.programs.find((p: { id: string }) => p.id === programId);
      if (program && program.versions.length > 0) {
        versionId = program.versions[0].id;
        break;
      }
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
    assert.ok(versionId, "expected a draft version to be generated");

    // Publish it.
    await request(app.getHttpServer())
      .post(`/v1/admin/programs/versions/${versionId}/publish`)
      .set("Cookie", cookie)
      .expect(201);

    // Public catalog now includes the program.
    const catalog = await request(app.getHttpServer()).get("/v1/programs").expect(200);
    const inCatalog = catalog.body.programs.find((p: { slug: string }) => p.slug === programSlug);
    assert.ok(inCatalog, "published program should appear in the public catalog");

    // Program content is the paid product: detail requires a session, and even
    // then returns a syllabus outline rather than lesson bodies or media URLs.
    await request(app.getHttpServer()).get(`/v1/programs/${programSlug}`).expect(401);

    const detail = await request(app.getHttpServer())
      .get(`/v1/programs/${programSlug}`)
      .set("Cookie", cookie)
      .expect(200);
    assert.ok(detail.body.program, "expected published program detail");
    assert.ok(detail.body.program.days.length > 0, "expected day outline");

    const outlineBlocks: { body: Record<string, unknown> | null; media: { url: string | null } | null }[] =
      detail.body.program.days.flatMap((day: { modules: { blocks: unknown[] }[] }) =>
        day.modules.flatMap((module) => module.blocks)
      );
    assert.ok(outlineBlocks.length > 0, "expected blocks in the outline");
    for (const block of outlineBlocks) {
      assert.equal(block.media?.url ?? null, null, "outline must not expose signed media URLs");
      const leaked = Object.keys(block.body ?? {}).filter((key) => key !== "heading" && key !== "title");
      assert.deepEqual(leaked, [], `outline leaked body fields: ${leaked.join(", ")}`);
    }

    console.log(`[authoring-smoke] PASS — create -> AI draft -> publish -> catalog (${detail.body.program.days.length} days).`);
  } finally {
    await prisma.experienceProgram.deleteMany({ where: { slug: programSlug } });
    await prisma.session.deleteMany({ where: { user: { email: adminEmail } } });
    await prisma.auditLog.deleteMany({ where: { actorUser: { email: adminEmail } } });
    await prisma.tenantMembership.deleteMany({ where: { user: { email: adminEmail } } });
    await prisma.user.deleteMany({ where: { email: adminEmail } });
    await prisma.tenant.deleteMany({ where: { slug: tenantSlug } });
    await worker.close();
    await app.close();
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
